version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - ${APACHE_PORT}:80
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - ${MYSQL_PORT}:3306    
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - /home/ubuntu/php-mysql-crud-docker/src/database/script.sql:/tmp/script.sql
    command: --init-file /tmp/script.sql
volumes:
  mysql_data:
